# Generated by Django 5.1.7 on 2025-03-31 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_code', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('running', 'Running'), ('finished', 'Finished')], default='open', max_length=10)),
                ('players', models.ManyToManyField(related_name='games', to='matchmaking.player')),
            ],
        ),
    ]
